log-pipeline :
  source :
     file:
      path: D:\project_aws\input.json
      format: json
      record_type: event
  sink :
    - kafka:
        tags_target_key: Tag
        bootstrap_servers:
          - "localhost:29092"
        thread_wait_time: 1000
        dlq:
          s3:
            bucket: "mydlqtestbucket"
            key_path_prefix: "dlq-files/"
            sts_role_arn: "arn:aws:iam::045129910014:role/dataprepper"
            region: "ap-south-1"
        partition_key: rec-${length(/Year)}
        serde_format: avro
        topic:
          name: doc_avro_shema_test2
          is_create: true
          number_of_partitions: 1
          replication_factor: 1
        schema:
          registry_url:  http://localhost:8085
          is_create: true
#          inline_schema: "{\n    \"schema\": \"{\\\"type\\\":\\\"record\\\",\\\"name\\\":\\\"MyRecord\\\",\\\"fields\\\":[{\\\"name\\\":\\\"message\\\",\\\"type\\\":\\\"string\\\"}]}\",\n    \"references\": [],\n    \"schemaType\": \"AVRO\",\n    \"name\": \"MySchema\"\n}"
          version: 1
#          basic_auth_credentials_source: USER_INFO
#          schema_registry_api_key: ZHGV4R77TKB6OLYZ
#          schema_registry_api_secret: k3VAJUh50MOrvxgKPC1xEE5s6tFvB+moAdK8xXM5/sp7eMaoiQ/sj5AKtbVFEjlu
          schema_file_location: D:\project_aws\schemadef.json
#          s3_file_config:
#            bucket_name: schemaconfuration
#            file_key: json_schema.txt
#            region: "ap-south-1"
        producer_properties:
          buffer_memory: 10mb
          compression_type: gzip
          retries: 3
          batch_size: 16384
          client_dns_lookup: use_all_dns_ips
          connections_max_idle: PT2M
          delivery_timeout: PT2M
          linger_ms: 0
          max_block: PT2M
          max_request_size: 1048576
          partitioner_class: org.apache.kafka.clients.producer.internals.DefaultPartitioner
          partitioner_ignore_keys: false
          receive_buffer: 3mb
          request_timeout: PT2M
          send_buffer: 2mb
          socket_connection_setup_timeout_max: PT2M
          socket_connection_setup_timeout: PT2M
          acks: all
          enable_idempotence: true
          max_in_flight_requests_per_connection: 5
          metadata_max_age: PT2M
          metadata_max_idle: PT2M
          metrics_num_samples: 2
          metrics_recording_level: INFO
          metrics_sample_window: PT2M
          partitioner_adaptive_partitioning_enable: true
          partitioner_availability_timeout: PT2M
          reconnect_backoff_max: PT2M
          reconnect_backoff: PT2M
          retry_backoff: PT2M
        authentication:
          sasl:
            plaintext:
              username: broker
              password: broker
